language: php
php:
  - 7.3
  - 7.4
before_script:
  - phpenv config-rm xdebug.ini
install:
  - composer install --no-dev --quiet
script: vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
    - bash <(curl -s https://codecov.io/bash)
